[settings]
minimum_release_age = "7d"

[tools]
"github:can1357/oh-my-pi" = "latest"
azure-cli = "latest"
bun = "1"
claude = "latest"
cmake = "latest"
codex = "latest"
dotnet = ["10", "8"]
gh = "latest"
go = "latest"
node = ["26", "24", "22"]
oh-my-pi = "latest"
pnpm = ["11", "10"]
python = ["3.14", "3.13"]
uv = "latest"
zig = "latest"

